### ISSUE TITLE
Assets with zero value throw errors on 'projections' tab

### ISSUE THREAD

**Issue by dominicbr** [tsumaru720/conspectus#25]
Assets that have 0 value currently throw division by zero errors when you view their 'projections' tab:

Warning:  Division by zero in /var/www/html/themes/default/app/projections.php on line 15
Warning:  Division by zero in /var/www/html/themes/default/app/projections.php on line 15
Warning:  A non-numeric value encountered in /var/www/html/themes/default/app/projections.php on line 14

**Comment by tsumaru720** [comment]
Those line numbers seem iffy - Managed to reproduce by adding a log entry of 0 deposit and 0 value though and I get these

https://github.com/tsumaru720/conspectus/blob/b2931f53d69d52bd96fba27be1332b30c8ad46fb/themes/default/app/projections.php#L154

https://github.com/tsumaru720/conspectus/blob/b2931f53d69d52bd96fba27be1332b30c8ad46fb/themes/default/app/projections.php#L140

**Comment by dominicbr** [comment]
My mistake - correct line numbers are:

Division by zero in /var/www/html/themes/default/app/projections.php on line 154
Division by zero in /var/www/html/themes/default/app/projections.php on line 154
A non-numeric value encountered in /var/www/html/themes/default/app/projections.php on line 140
