### ISSUE TITLE
Window size and scroll bars

### ISSUE THREAD

**Issue by tsumaru720** [tsumaru720/conspectus#3]
At certain window sizes, the content is just long enough that the scroll bar is needed - chartjs will dutifully resize its width to accommodate which means it no longer needs the scroll bar - so resizes to fit... rinse .. repeat

Reproducable on Breakdown at
`Window: 1920px x 1031px     Viewport: 1920px x 927px`

and Dashboard at
`Window: 1917px x 1097px     Viewport: 1917px x 993px`

(via @shanemcc)

**Comment by ShaneMcC** [comment]
`Window: 1272px x 763px     Viewport: 1272px x 659px` as a smaller size setting for the same thing on breakdown :D

**Comment by tsumaru720** [comment]
Duplicate of #63
