### ISSUE TITLE
Asset/class name limits are bytes not chars which is confusing

### ISSUE THREAD

**Issue by csmith** [tsumaru720/conspectus#61]
If you use emojis (or other unicode chars) in the name of a class/asset then the length limit is wonky.

e.g. my browser will happily let me enter

> 🧑‍🚀🧑‍🚀🧑‍🚀🧑‍🚀🧑‍🚀🧑‍🚀🧑‍🚀🧑‍🚀

but after submitting it, Conspectus says:

> Asset name is too long - Max: 40

I can in fact only use three white astronauts, or two black astronauts. Any more are rejected.

Ideally the backend should work in characters not bytes so it's consistent with browsers, not confusing to users, and not mildly racist

**Comment by tsumaru720** [comment]
See https://github.com/tsumaru720/conspectus/commit/de58e64fd7500e80d89815ab0b53e6122ef89dbc
