### ISSUE TITLE
Jiggling layout

### ISSUE THREAD

**Issue by greboid** [tsumaru720/conspectus#63]
If you resize the window to a certain point it adds the scrollbar, which causes the graphs to resize, which removes the scrollbar etc etc.

Not sure its a priority or worth fixing really, but see attached.

https://user-images.githubusercontent.com/189618/124028211-a6911500-d9eb-11eb-82f2-6bf481be3ffe.mp4

**Comment by tsumaru720** [comment]
fixed in dd6e008fe767c7e4651dda98e1f79741201ad524
