### ISSUE TITLE
Small screen layout broken

### ISSUE THREAD

**Issue by greboid** [tsumaru720/conspectus#64]
When you go to a certain screen width, you lose left menu completely.
![jv6shgq4](https://user-images.githubusercontent.com/189618/124028642-27e8a780-d9ec-11eb-8540-7fd199bb45bd.png)
![wpqcf5ee](https://user-images.githubusercontent.com/189618/124028645-2919d480-d9ec-11eb-9677-de88d04bd55b.png)

**Comment by tsumaru720** [comment]
Kinda ties in with #14 so going to close this one
