### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by tsumaru720** [tsumaru720/conspectus#81]
@dominicbr wants a favicon

Dominic — Today at 14:31
https://favicon.io/emoji-favicons/money-with-wings
or anything similar
https://favicon.io/emoji-favicons/money-bag/ maybe

**Comment by csmith** [comment]
What about a coin with a cent symbol on it? Then it's both money and a "c" for "conspectus"?

Like this but less bad?
![image](https://user-images.githubusercontent.com/189133/236487129-54c43511-5c84-41c1-9d16-ad613152dda6.png)
