### ISSUE TITLE
PHP errors when viewing an asset that doesn't exist

### ISSUE THREAD

**Issue by ShaneMcC** [tsumaru720/conspectus#9]
Example: https://demo.money.agari.co/view/class/999

```
Notice: Undefined variable: last in /home/demomoney/public_html/themes/default/app/item_view.php on line 129

Notice: Undefined index: asset_total in /home/demomoney/public_html/themes/default/app/item_view.php on line 130

Notice: Undefined index: gain in /home/demomoney/public_html/themes/default/app/item_view.php on line 131
```

**Comment by tsumaru720** [comment]
So this only actually seems to be an issue when trying to view a class id that doesn't exist.

The code for this is initially based on how the asset id check works, in that it attempts to grab it from the database and if the query returns no results, it errors.

With Classes however, I specifically provide the number of assets in the class as a count() field (primarily  to enable/disable buttons based on if there is only one asset on display).

This seems to have a side effect that using count will always return results from the database, namely a count of 0 and NULL as the asset description

```
array(2) {
  ["count"]=>
  string(1) "0"
  ["description"]=>
  string(6) "NULL"
}
```

Checking count > 0 will fix this

**Comment by tsumaru720** [comment]
Checking count > 0 alone will error when we add a class which has no assets in it, so will need to check both count is > 0 and description is not NULL
